package tether

import (
	"io/fs"
	"net/http"
	"strconv"
	"strings"
	"sync"

	"github.com/andybalholm/brotli"
	"github.com/jpl-au/tether/dev"
	"github.com/klauspost/compress/gzip"
)

// The names of the client files that need special handling. Every other
// served script is an ordinary first-party asset.
const (
	clientIdiomorph  = "idiomorph.min.js" // byte-identical, never re-minified
	clientWorker     = "tether-worker.js" // dynamic body, built at serve time
	clientPushWorker = "tether-push-worker.js"
)

// jsContentType is the wire Content-Type for every client script. It
// matches what net/http's FileServer returns for a .js file and is a
// valid JavaScript MIME type for classic scripts, module scripts, and
// service workers alike.
const jsContentType = "text/javascript; charset=utf-8"

// clientAsset holds the wire representations of one served client file:
// the identity (minified) bytes plus precompressed gzip and brotli
// variants. A nil variant means that encoding is unavailable and the
// handler falls back to a smaller-preference encoding or identity.
type clientAsset struct {
	identity []byte
	gzip     []byte
	brotli   []byte
}

var (
	clientAssetsOnce sync.Once
	clientAssetsMap  map[string]clientAsset
)

// clientAssets returns the production asset registry keyed by URL path
// (e.g. "tether.js"). It is built once from the embedded client/dist
// directory generated by `go generate` (see gen_client.go). The service
// worker is intentionally absent: its bytes are assembled per
// application at serve time and compressed then.
func clientAssets() map[string]clientAsset {
	clientAssetsOnce.Do(func() {
		clientAssetsMap = buildClientAssets()
	})
	return clientAssetsMap
}

func buildClientAssets() map[string]clientAsset {
	dist, err := fs.Sub(clientFS, "client/dist")
	if err != nil {
		// The embed directive guarantees client/dist exists once
		// `go generate` has run. A failure here means a broken build.
		panic("tether: embedded client/dist missing: " + err.Error())
	}

	assets := map[string]clientAsset{}

	// idiomorph.min.js is served byte-identical from its source file (it
	// is sha256-verified against the npm dist and must not be rewritten);
	// only its compressed variants are generated into dist.
	idSrc, err := fs.ReadFile(clientFiles(), clientIdiomorph)
	if err != nil {
		panic("tether: embedded " + clientIdiomorph + " missing: " + err.Error())
	}
	assets[clientIdiomorph] = clientAsset{
		identity: idSrc,
		gzip:     mustReadDist(dist, clientIdiomorph+".gz"),
		brotli:   mustReadDist(dist, clientIdiomorph+".br"),
	}

	// Every remaining plain (un-suffixed) dist entry is a minified
	// first-party script with gzip and brotli siblings. The worker
	// template is skipped because it is served dynamically, not from
	// this registry.
	entries, err := fs.ReadDir(dist, ".")
	if err != nil {
		panic("tether: reading embedded client/dist: " + err.Error())
	}
	for _, e := range entries {
		name := e.Name()
		if strings.HasSuffix(name, ".gz") || strings.HasSuffix(name, ".br") {
			continue
		}
		if name == clientWorker || name == clientIdiomorph {
			continue
		}
		assets[name] = clientAsset{
			identity: mustReadDist(dist, name),
			gzip:     mustReadDist(dist, name+".gz"),
			brotli:   mustReadDist(dist, name+".br"),
		}
	}
	return assets
}

func mustReadDist(dist fs.FS, name string) []byte {
	data, err := fs.ReadFile(dist, name)
	if err != nil {
		panic("tether: embedded client/dist/" + name + " missing: " + err.Error())
	}
	return data
}

// compressAsset builds a clientAsset from identity bytes, compressing
// them into gzip and brotli variants at maximum quality. Used for the
// service worker, whose body is assembled per application at serve time
// and so cannot be precompressed by `go generate`. Called once per
// handler, so the one-off brotli cost is paid at startup, not per
// request.
func compressAsset(identity []byte) clientAsset {
	return clientAsset{
		identity: identity,
		gzip:     gzipBytes(identity),
		brotli:   brotliBytes(identity),
	}
}

func gzipBytes(body []byte) []byte {
	var buf strings.Builder
	w, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return nil
	}
	if _, err := w.Write(body); err != nil {
		return nil
	}
	if err := w.Close(); err != nil {
		return nil
	}
	return []byte(buf.String())
}

func brotliBytes(body []byte) []byte {
	var buf strings.Builder
	w := brotli.NewWriterLevel(&buf, brotli.BestCompression)
	if _, err := w.Write(body); err != nil {
		return nil
	}
	if err := w.Close(); err != nil {
		return nil
	}
	return []byte(buf.String())
}

// writeClientAsset negotiates Accept-Encoding and writes the best
// available representation with the correct headers. Vary is always set
// so shared caches key their stored copies on Accept-Encoding.
func writeClientAsset(w http.ResponseWriter, r *http.Request, a clientAsset) {
	h := w.Header()
	h.Set("Content-Type", jsContentType)
	h.Set("Vary", "Accept-Encoding")

	body := a.identity
	switch negotiateEncoding(r.Header.Get("Accept-Encoding")) {
	case "br":
		if a.brotli != nil {
			h.Set("Content-Encoding", "br")
			body = a.brotli
		}
	case "gzip":
		if a.gzip != nil {
			h.Set("Content-Encoding", "gzip")
			body = a.gzip
		}
	}
	h.Set("Content-Length", strconv.Itoa(len(body)))
	if _, err := w.Write(body); err != nil {
		dev.Log().Warn("tether: failed to write client asset", "err", err)
	}
}

// negotiateEncoding picks the best supported Content-Encoding from an
// Accept-Encoding header. Brotli is preferred over gzip because it is
// materially smaller for our assets. An explicit "q=0" disqualifies an
// encoding (a bare "*" only supplies a default for unlisted ones).
// Returns "" for identity.
func negotiateEncoding(accept string) string {
	q := map[string]float64{}
	for _, part := range strings.Split(accept, ",") {
		token := strings.TrimSpace(part)
		if token == "" {
			continue
		}
		name := token
		val := 1.0
		if i := strings.IndexByte(token, ';'); i >= 0 {
			name = strings.TrimSpace(token[:i])
			val = parseQ(token[i+1:])
		}
		q[strings.ToLower(name)] = val
	}

	allowed := func(name string) bool {
		if v, ok := q[name]; ok {
			return v > 0
		}
		if v, ok := q["*"]; ok {
			return v > 0
		}
		return false
	}

	switch {
	case allowed("br"):
		return "br"
	case allowed("gzip"):
		return "gzip"
	default:
		return ""
	}
}

// parseQ extracts the q-value from the parameters after an
// Accept-Encoding token's semicolon. Absent or malformed q defaults to
// 1 (fully acceptable).
func parseQ(params string) float64 {
	for _, p := range strings.Split(params, ";") {
		p = strings.TrimSpace(p)
		if v, ok := strings.CutPrefix(p, "q="); ok {
			f, err := strconv.ParseFloat(strings.TrimSpace(v), 64)
			if err != nil {
				return 1
			}
			return f
		}
	}
	return 1
}
