package poly

import "net/url"

// Event is the message the client sends to the server when the user
// interacts with the page. The client JS intercepts DOM events on
// elements annotated with data-poly-* attributes and serialises them
// into this structure.
//
// Type is the DOM event name (e.g. "click", "input", "submit",
// "navigate"). Action is the value of the data-poly-* attribute —
// it is the application-defined name that the Handle function switches
// on. Data carries event-specific key-value pairs: for input events
// this is {"value": "..."}, for submit events it includes all named
// form fields, and for keydown events it includes {"key": "Enter"}.
//
// EventID is a monotonically increasing counter generated by the
// client JS and echoed back in the server's response. The client uses
// it to correlate responses with specific events, which allows loading
// state indicators (e.g. disabled buttons) to be restored on exactly
// the element that triggered the action rather than globally.
type Event struct {
	Type    string            `json:"type"`
	Action  string            `json:"action"`
	Data    map[string]string `json:"data,omitempty"`
	EventID string            `json:"event_id,omitempty"`
}

// Params carries URL information from a navigation event. The handler
// passes this to Config.HandleParams on the initial page load (so the
// application can derive state from the URL) and whenever the browser
// navigates via a poly link click or the back/forward buttons.
type Params struct {
	Path  string
	Query url.Values
}
