package tether

import (
	"strconv"

	"github.com/jpl-au/tether/event"
)

// Event is the message the client sends to the server when the user
// interacts with the page. The client JS intercepts DOM events on
// elements annotated with data-tether-* attributes and serialises them
// into this structure.
//
// Event and [Params] are the two data extraction types in the
// framework. Event represents DOM interactions (clicks, inputs,
// submits); Params represents URL navigation context (path and query
// string). Both share a similar helper API (Get, Int, Float64, Bool)
// so developers learn one extraction pattern. Params additionally has
// soft getters (IntOr, BoolOr, Float64Or) because URL parameters are
// user-supplied and routinely absent, whereas event data is developer-
// controlled wire protocol where absence signals a bug. Params lives
// in params.go.
//
// Type is the DOM [event.Type] (e.g. [event.Click], [event.Input],
// [event.Submit], [event.Navigate]). Action is the value of the
// data-tether-* attribute — it is the application-defined name that the
// Handle function switches on. Data carries event-specific key-value
// pairs: for input events this is {"value": "..."}, for submit events
// it includes all named form fields, and for keydown events it
// includes {"key": "Enter"}.
//
// Target identifies which component handled this event. It is empty for
// events routed to the application's Handle function, and set by the
// framework when [StatefulConfig.Components] dispatches an event to a mounted
// component. Middleware and logging can inspect Target to see which
// component an event was routed to without parsing the Action string.
//
// EventID is a monotonically increasing counter generated by the
// client JS and echoed back in the server's response. The client uses
// it to correlate responses with specific events, which allows loading
// state indicators (e.g. disabled buttons) to be restored on exactly
// the element that triggered the action rather than globally.
type Event struct {
	Type    event.Type        `json:"type"`
	Action  string            `json:"action"`
	Target  string            `json:"target,omitempty"`
	Data    map[string]string `json:"data,omitempty"`
	EventID string            `json:"event_id,omitempty"`
}

// Value returns the input element's value from the event data. This is
// a convenience for ev.Data["value"], which the client JS populates
// automatically for input and change events.
func (e Event) Value() string {
	return e.Data["value"]
}

// Key returns the key name from a keydown event. This is a convenience
// for ev.Data["key"], which the client JS populates automatically for
// keydown events (e.g. "Enter", "Escape", "ArrowUp").
func (e Event) Key() string {
	return e.Data["key"]
}

// Get returns the value for a data key and reports whether it was present.
func (e Event) Get(key string) (string, bool) {
	v, ok := e.Data[key]
	return v, ok
}

// Int returns the data value for key parsed as an integer. If the key
// is missing or the value is not a valid integer, it returns 0 and an
// error.
func (e Event) Int(key string) (int, error) {
	return strconv.Atoi(e.Data[key])
}

// Float64 returns the data value for key parsed as a float. If the key
// is missing or the value is not a valid number, it returns 0 and an
// error.
func (e Event) Float64(key string) (float64, error) {
	return strconv.ParseFloat(e.Data[key], 64)
}

// Bool returns true when the data value for key is the string "true".
// All other values — including missing keys — return false.
func (e Event) Bool(key string) bool {
	return e.Data[key] == "true"
}

// WithAction returns a copy of the event with a different Action.
// Used by [Route] and [RouteTyped] to strip the component prefix
// before forwarding the event to a component's Handle method.
func (e Event) WithAction(action string) Event {
	e.Action = action
	return e
}
