package tether

import xport "github.com/jpl-au/tether/internal/transport"

// Event is the message the client sends to the server when the user
// interacts with the page. The client JS intercepts DOM events on
// elements annotated with data-tether-* attributes and serialises them
// into this structure.
//
// Event and [Params] are the two data extraction types in the
// framework. Event represents DOM interactions (clicks, inputs,
// submits); Params represents URL navigation context (path and query
// string). Both share a similar helper API (Get, Int, Float64, Bool)
// so developers learn one extraction pattern. Params additionally has
// soft getters (IntDefault, BoolDefault, Float64Default) because URL parameters are
// user-supplied and routinely absent, whereas event data is developer-
// controlled wire protocol where absence signals a bug. Params lives
// in params.go.
//
// Type is the DOM [event.Type] (e.g. [event.Click], [event.Input],
// [event.Submit], [event.Navigate]). Action is the value of the
// data-tether-* attribute - it is the application-defined name that the
// Handle function switches on. Data carries event-specific key-value
// pairs: for input events this is {"value": "..."}, for submit events
// it includes all named form fields, and for keydown events it
// includes {"key": "Enter"}.
//
// Target identifies which component handled this event. It is empty for
// events routed to the application's Handle function, and set by the
// framework when [StatefulConfig.Components] dispatches an event to a mounted
// component. Middleware and logging can inspect Target to see which
// component an event was routed to without parsing the Action string.
//
// EventID is a monotonically increasing counter generated by the
// client JS and echoed back in the server's response. The client uses
// it to correlate responses with specific events, which allows loading
// state indicators (e.g. disabled buttons) to be restored on exactly
// the element that triggered the action rather than globally.
type Event = xport.Event
