package transport

import (
	"fmt"
	"reflect"
	"strconv"

	"github.com/jpl-au/tether/event"
)

// Event is the message the client sends to the server when the user
// interacts with the page. The client JS intercepts DOM events on
// elements annotated with data-tether-* attributes and serialises them
// into this structure.
//
// Type is the DOM event type (e.g. click, input, submit, navigate).
// Action is the application-defined name that the Handle function
// switches on. Data carries event-specific key-value pairs.
//
// EventID is a monotonically increasing counter generated by the
// client JS and echoed back in the server's response. The client uses
// it to correlate responses with specific events.
type Event struct {
	Type    event.Type        `json:"type"`
	Action  string            `json:"action"`
	Target  string            `json:"target,omitempty"`
	Data    map[string]string `json:"data,omitempty"`
	EventID string            `json:"event_id,omitempty"`
}

// Value returns the input element's value from the event data. This is
// a convenience for ev.Data["value"], which the client JS populates
// automatically for input and change events.
func (e Event) Value() string {
	return e.Data["value"]
}

// Key returns the key name from a keydown event. This is a convenience
// for ev.Data["key"], which the client JS populates automatically for
// keydown events (e.g. "Enter", "Escape", "ArrowUp").
func (e Event) Key() string {
	return e.Data["key"]
}

// Get returns the value for a data key and reports whether it was present.
func (e Event) Get(key string) (string, bool) {
	v, ok := e.Data[key]
	return v, ok
}

// Int returns the data value for key parsed as an integer. If the key
// is missing or the value is not a valid integer, it returns 0 and an
// error.
func (e Event) Int(key string) (int, error) {
	return strconv.Atoi(e.Data[key])
}

// Float64 returns the data value for key parsed as a float. If the key
// is missing or the value is not a valid number, it returns 0 and an
// error.
func (e Event) Float64(key string) (float64, error) {
	return strconv.ParseFloat(e.Data[key], 64)
}

// Bool returns true when the data value for key is the string "true".
// All other values - including missing keys - return false.
func (e Event) Bool(key string) bool {
	return e.Data[key] == "true"
}

// WithAction returns a copy of the event with a different Action.
// Used by component routing to strip the component prefix before
// forwarding the event to a component's Handle method.
func (e Event) WithAction(action string) Event {
	e.Action = action
	return e
}

// Bind decodes the event's Data map into a struct. Fields are matched
// by the "tether" struct tag; untagged exported fields use their
// lowercased name. Supported field types: string, int, int64, float64,
// bool.
//
// This is the multi-field counterpart to the single-value helpers
// (Value, Key, Int, Bool). Use Bind when a form submit sends several
// named fields at once:
//
//	var form struct {
//	    Email string `tether:"email"`
//	    Age   int    `tether:"age"`
//	}
//	if err := ev.Bind(&form); err != nil {
//	    s.TodoError = err.Error()
//	    return s
//	}
func (e Event) Bind(dest any) error {
	rv := reflect.ValueOf(dest)
	if rv.Kind() != reflect.Pointer || rv.IsNil() {
		return fmt.Errorf("tether: Bind requires a non-nil pointer, got %T", dest)
	}
	rv = rv.Elem()
	if rv.Kind() != reflect.Struct {
		return fmt.Errorf("tether: Bind requires a pointer to a struct, got *%s", rv.Type())
	}
	rt := rv.Type()
	for i := range rt.NumField() {
		f := rt.Field(i)
		if !f.IsExported() {
			continue
		}
		key := f.Tag.Get("tether")
		if key == "" {
			key = lowercaseFirst(f.Name)
		}
		raw, ok := e.Data[key]
		if !ok {
			continue
		}
		if err := setField(rv.Field(i), raw, key); err != nil {
			return err
		}
	}
	return nil
}

func setField(fv reflect.Value, raw, key string) error {
	switch fv.Kind() {
	case reflect.String:
		fv.SetString(raw)
	case reflect.Int, reflect.Int64:
		n, err := strconv.ParseInt(raw, 10, fv.Type().Bits())
		if err != nil {
			return fmt.Errorf("tether: field %q: %w", key, err)
		}
		fv.SetInt(n)
	case reflect.Float64:
		n, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			return fmt.Errorf("tether: field %q: %w", key, err)
		}
		fv.SetFloat(n)
	case reflect.Bool:
		fv.SetBool(raw == "true")
	default:
		return fmt.Errorf("tether: unsupported field type %s for key %q", fv.Type(), key)
	}
	return nil
}

// lowercaseFirst returns s with the first byte lowercased. This
// matches the convention of HTML form field names being lowercase
// versions of Go exported field names.
func lowercaseFirst(s string) string {
	if s == "" {
		return s
	}
	b := []byte(s)
	if b[0] >= 'A' && b[0] <= 'Z' {
		b[0] += 'a' - 'A'
	}
	return string(b)
}
